name: ui_badge
description: "A Badge widget to show a number in a circle with a background color."
version: 0.2.0
home_page: http://www.icodeforyou.com
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0" # % flutter --version => values of "Dart"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  # logger: ^2.2.0 # Uncomment this line to use logger package {better than debugPrint}
  ui_extensions_flutter:
    git: https://github.com/GitHubStuff/ui_extensions_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
